# Generated by Django 5.1.1 on 2024-10-14 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='time published'),
            preserve_default=False,
        ),
    ]
